name: SSH
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Publish new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run lib:build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

